/*
\\yngcompany
*/
var projectData = [
	{
		"id": 23010930,
		"subject": "옴니서비스 소개",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 11,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010929,
		"subject": "광군절 결제사 적립금 LDF PAY 증정",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 10,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010928,
		"subject": "10월 테마 기획전 향기로 채우는 공간",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 10,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010927,
		"subject": "온라인 단독 라운지 기획전",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 9,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010926,
		"subject": "강추특가 기획전",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 9,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010925,
		"subject": "골프관 브랜드 기획전 페이지",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 8,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010924,
		"subject": "건강식품 기획전",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 7,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010923,
		"subject": "선글라스 기획전",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 7,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010922,
		"subject": "선크림 기획전",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 7,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010921,
		"subject": "휴양지에서의 패션 기획전",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 5,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010920,
		"subject": "지구를 응원해 기획전",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 4,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010919,
		"subject": "가방 기획전 트리플 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 3,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010918,
		"subject": "연말결산 베스트어워즈 구매왕 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 11,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010917,
		"subject": "블랙프라이데이 온오프 혜택 증정 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 11,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010916,
		"subject": "블랙프라이데이 기획전",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 11,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010915,
		"subject": "현대카드 3차 프로모션 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 9,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010914,
		"subject": "오프라인 혜택총집합",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 8,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010913,
		"subject": "온라인 혜택총집합",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 8,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010912,
		"subject": "골프관 오픈 기념 경품 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 8,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010911,
		"subject": "현대카드 오픈 기념 경품 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 6,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23010910,
		"subject": "여름엔 너 하나면 돼 원피스 기획전",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 6,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 2301099,
		"subject": "썸머바캉스 프로모션",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 6,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 2301098,
		"subject": "롯데면세점X현대카드 혜택안내 페이지",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 5,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 2301097,
		"subject": "트래블버블성 이벤트 혜택 총집합",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 5,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 2301095,
		"subject": "프리퀀시 오픈기념 경품 증정 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 4,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 2301094,
		"subject": "트레블이즈커밍",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 4,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 2301093,
		"subject": "42주년 코스메틱 브랜드 적립금 증정 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 2,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 2301092,
		"subject": "면세 구매한도 퀴즈 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 2,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 230109,
		"subject": "42주년 온오프라인 혜택 증정 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 1,
		"thumbnail": "thumbnail.png",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},

	{
		"id": 1,
		"subject": "오프라인 고객 대상 전세기 티켓 증정 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2022,
		"month": 1,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 30,
		"subject": "신년 목표달성 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2021,
		"month": 122,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 29,
		"subject": "신년 더드림 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2021,
		"month": 12,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 225,
		"subject": "롯데인터넷면세점 운영 제안",
		"type": "제안",
		"detail": "시안",
		"year": 2021,
		"month": 12,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "../../../../lotte/",
		"cowork": ""
	},
	{
		"id": 224,
		"subject": "신세계 백화점 운영 제안",
		"type": "제안",
		"detail": "시안",
		"year": 2021,
		"month": 11,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "../../../../shinsegae/",
		"cowork": ""
	},
	{
		"id": 28,
		"subject": "친구 초대 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2021,
		"month": 112,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 27,
		"subject": "광군절 본행사",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2021,
		"month": 11,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 26,
		"subject": "광군절 예열 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2021,
		"month": 10,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 223,
		"subject": "신세계프라퍼티",
		"type": "제안",
		"detail": "시안",
		"year": 2021,
		"month": 9,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "../../../../property/index.html",
		"cowork": ""
	},
	{
		"id": 25,
		"subject": "무신사 솔드아웃 이벤트 2차",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2021,
		"month": 7,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 24,
		"subject": "무신사 솔드아웃 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2021,
		"month": 6,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 31,
		"subject": "아시아나 무착륙 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2021,
		"month": 42,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 23,
		"subject": "웨딩 사연 및 괌 패키지 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2021,
		"month": 4,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 222,
		"subject": "AK PLAZA",
		"type": "제안",
		"detail": "시안",
		"year": 2021,
		"month": 3,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "../../../../AKPLAZA/html.html",
		"cowork": ""
	},
	{
		"id": 22,
		"subject": "무착륙 전용혜택 통합 페이지",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2021,
		"month": 3,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
	{
		"id": 21,
		"subject": "가상 쇼핑 경품 증정 이벤트",
		"type": "운영",
		"detail": "롯데인터넷면세점",
		"year": 2021,
		"month": 1,
		"thumbnail": "thumbnail.jpg",
		"view": "h",
		"url": "index.html",
		"cowork": ""
	},
];